### ISSUE TITLE
Add an exFAT fs driver

### ISSUE THREAD

**Issue by mkopec** [Dasharo/meta-dts#38]
It would be convenient to be able to use exFAT-formatted flash drives in DTS without reformatting them first.

**Comment by miczyg1** [comment]
We could also add NTFS if we needed to take some logs from Windows installations

**Comment by DaniilKl** [comment]
> exFAT-formatted

Do you mean that we need to add exFAT fs support?

**Comment by mkopec** [comment]
@DaniilKl yes, that's what I meant. I guess `CONFIG_EXFAT_FS` in kernel config should be set to `y` or `m`

**Comment by DaniilKl** [comment]
Added to future release via [this PR](https://github.com/Dasharo/meta-dts/pull/44)

**Comment by mkopec** [comment]
Confirmed to be fixed in 1.2.13-rc2.
